### ISSUE TITLE
Unclear use case

### ISSUE THREAD

**Issue by michaelaye** [ProAdd-ons/vscode-LaTeX-support#4]
Could you make clear in the README please if this can be used as an add-on to the Latex Workshop or if this is an alternative to the Latex Workshop?

thanks!

**Comment by torn4dom4n** [comment]
Hi @michaelaye, my extension is only support for syntax. It is not an add-on to the Latex Workshop. I converted it from textmate and improved it, you can try something like `minted`, folding, etc. I think my README is clear.

**Comment by torn4dom4n** [comment]
You can compare the highlight in [text.tex](https://github.com/ProAdd-ons/vscode-LaTeX-support/blob/master/tests/text.tex) between Latex Workshop and my syntax.
