### ISSUE TITLE
$ within minted code blocks breaks highlighting

### ISSUE THREAD

**Issue by pshirshov** [ProAdd-ons/vscode-LaTeX-support#6]
Example: https://github.com/7mind/slides/blob/master/01-logstage/logstage.tex#L90

<img width="556" alt="screenshot 2018-10-23 at 00 51 36" src="https://user-images.githubusercontent.com/295225/47325872-df369900-d65d-11e8-9d72-e2193eeb718a.png">

**Comment by torn4dom4n** [comment]
Thank @pshirshov for your report!

**Comment by pshirshov** [comment]
In fact it's still broken. 

Fails on this file: https://github.com/7mind/slides/blob/master/04-distage/distage.tex

**Comment by torn4dom4n** [comment]
Sorry for the delay. I fixed it in v3.0.0. Thank you so much.
